/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DemoAppAdaptor -a demoappadaptor.h:demoappadaptor.cpp com.jolla.transferdemoapp.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DEMOAPPADAPTOR_H_1359378204
#define DEMOAPPADAPTOR_H_1359378204

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.jolla.transferdemoapp
 */
class DemoAppAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.jolla.transferdemoapp")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.jolla.transferdemoapp\">\n"
"\n"
"        # cancel a specific transfer\n"
"        <method name=\"cancelTransfer\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"transferId\"/>\n"
"    </method>\n"
"\n"
"        # enable or disable notifications\n"
"        <method name=\"restartTransfer\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"transferId\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DemoAppAdaptor(QObject *parent);
    virtual ~DemoAppAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void cancelTransfer(int transferId);
    void restartTransfer(int transferId);
Q_SIGNALS: // SIGNALS
};

#endif
