/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DemoAppAdaptor -a demoappadaptor.h:demoappadaptor.cpp com.jolla.transferdemoapp.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "demoappadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DemoAppAdaptor
 */

DemoAppAdaptor::DemoAppAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DemoAppAdaptor::~DemoAppAdaptor()
{
    // destructor
}

void DemoAppAdaptor::cancelTransfer(int transferId)
{
    // handle method call com.jolla.transferdemoapp.cancelTransfer
    QMetaObject::invokeMethod(parent(), "cancelTransfer", Q_ARG(int, transferId));
}

void DemoAppAdaptor::restartTransfer(int transferId)
{
    // handle method call com.jolla.transferdemoapp.restartTransfer
    QMetaObject::invokeMethod(parent(), "restartTransfer", Q_ARG(int, transferId));
}

